### ISSUE TITLE
Can't get Docker Image - Unauthorized

### ISSUE THREAD

**Issue by nilansaha** [facebookincubator/cinder#15] opened 2021-05-07 01:47 UTC
When I try to run
```
docker run -v "$PWD/cinder:/vol" -w /vol -ti ghcr.io/facebookincubator/cinder/python-build-env:latest bash
```

I get 
```
Unable to find image 'ghcr.io/facebookincubator/cinder/python-build-env:latest' locally
docker: Error response from daemon: Get https://ghcr.io/v2/facebookincubator/cinder/python-build-env/manifests/latest: unauthorized.
See 'docker run --help'.
```

**Comment by aisk** [comment] 2021-05-11 07:27
I think you're not login into github's docker repositry. See https://docs.github.com/en/packages/quickstart to how to login.

**Comment by aisk** [comment] 2021-05-11 11:19
After login, there still some issue for pulling the image, I think it's caused by the permission settings of this repo. But I think you can using the Dockerfile in `.github/` folders for build your image.

**Comment by jbower-fb** [comment] 2021-05-11 21:19
Thanks @nilansaha and @aisk for reporting and looking into this. Turns out the package was marked as "private", and I didn't notice this when testing my updates to the README as my credentials were stored in my local config. I believe the package should be available for public download now so I'm closing this issue, but feel free to re-open if you're still having problems.

**Closed as completed by jbower-fb** 2021-05-11 21:19 UTC

**Comment by aisk** [comment] 2021-05-12 08:32
@jbower-fb After login into ghcr.io the image can be pulled successfully, thanks!
